name: Bug report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: scratchattach-version
    attributes:
      label: scratchattach version
      description: The version of scratchattach you have installed. Can be found using `python -m pip show scratchattach`
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Your code.
      description: Put your code here. Be careful not to reveal your login data.
      render: python
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      description: If you received a traceback, please copy paste the full traceback here. Otherwise write "none".
      render: txt
    validations:
      required: true
