"""
URL query language codes for https://scratchblocks.github.io/
"""

LANGUAGES = {'Select language…\n  ': '',
             '': '',

             'Аҧсшәа': 'ab',
             'Afrikaans': 'af',
             'አማርኛ': 'am',
             'Aragonés': 'an',
             'العربية': 'ar',
             'Asturianu': 'ast',
             'Azeri': 'az',
             'Беларуская': 'be',
             'Български': 'bg',
             'বাংলা': 'bn',
             'Català': 'ca',
             'کوردیی ناوەندی': 'ckb',
             'Česky': 'cs',
             'Cymraeg': 'cy',
             'Dansk': 'da',
             'Deutsch': 'de',
             'Ελληνικά': 'el',
             'English': 'en',
             'Esperanto': 'eo',
             'Español (España)': 'es',
             'Español': 'es',
             'Español Latinoamericano': 'es_419',
             'Eesti': 'et',
             'Euskara': 'eu',
             'فارسی': 'fa',
             'Suomi': 'fi',
             'Filipino': 'fil',
             'Français': 'fr',
             'Frysk': 'fy',
             'Gaeilge': 'ga',
             'Gàidhlig': 'gd',
             'Galego': 'gl',
             'Hausa': 'ha',
             'עִבְרִית': 'he',
             'हिंदी': 'hi',
             'Hrvatski': 'hr',
             'Kreyòl ayisyen': 'ht',
             'Magyar': 'hu',
             'Հայերեն': 'hy',
             'Bahasa Indonesia': 'id',
             'Íslenska': 'is',
             'Italiano': 'it',
             '日本語': 'ja',
             'にほんご': 'ja_Hira',
             'ქართული ენა': 'ka',
             'қазақша': 'kk',
             'ភាសាខ្មែរ': 'km',
             '한국어': 'ko',
             'Kurdî': 'ku',
             'Lietuvių': 'lt',
             'Latviešu': 'lv',
             'Māori': 'mi',
             'Монгол хэл': 'mn',
             'Norsk Bokmål': 'nb',
             'Nederlands': 'nl',
             'Norsk Nynorsk': 'nn',
             'Sepedi': 'nso',
             'Occitan': 'oc',
             'ଓଡ଼ିଆ': 'or',
             'Polski': 'pl',
             'Português': 'pt',
             'Português Brasileiro': 'pt_br',
             'Kichwa': 'qu',
             'Rapa Nui': 'rap',
             'Română': 'ro',
             'Русский': 'ru',
             'Slovenčina': 'sk',
             'Slovenščina': 'sl',
             'Српски': 'sr',
             'Svenska': 'sv',
             'Kiswahili': 'sw',
             'ไทย': 'th',
             'Setswana': 'tn',
             'Türkçe': 'tr',
             'Українська': 'uk',
             'Oʻzbekcha': 'uz',
             'Tiếng Việt': 'vi',
             'isiXhosa': 'xh',
             '简体中文': 'zh_cn',
             '繁體中文': 'zh_tw',
             'isiZulu': 'zu'}
